"""Hadith marking + takhrij + grading status (CLAUDE.md §4.4, §12.B1, §12.D3).

A hadith unit = the narration (body: «وعن أبي هريرة …») + the quoted wording (hadith
blocks) + al-Nawawi's takhrij («متفق عليه» / «رواه مسلم» …) that follows it.

Grading rule (never generated by an LLM):
  - takhrij names al-Bukhari and/or Muslim (incl. متفق عليه, «رواه إماما المحدثين») ->
    grading_status = "in_sahihayn"; source = the printed takhrij.
  - otherwise -> grading from dorar.net entered by a human (with the result URL), stored in
    data/hadith_gradings.json -> grading_status = "verified".
  - no entered grading -> "unverified" -> UI shows «الحكم غير متحقق في البيانات».
HadeethEnc matches are attached as a second reference (display only).
"""

from __future__ import annotations

import json
import re
import urllib.parse

from pipeline.config import DATA
from pipeline.normalize import normalize

GRADINGS = DATA / "hadith_gradings.json"
UNVERIFIED_AR = "الحكم غير متحقق في البيانات"

_D = r"[ً-ْٰ]*"  # optional tashkeel between letters
TAKHRIJ_RE = re.compile(r"(متفق\s*عل[يى]ه|(?:رواه|أخرجه)\s+[^.«»\n]{2,90})")
SAHIHAYN_RE = re.compile(r"متفق|البخار|مسلم|إماما المحدثين|اماما المحدثين")
START_RE = re.compile(r"^\s*(و?عن|و?روينا)\s")  # «وفى رواية» = variant of the same unit


def classify_takhrij(takhrij: str | None) -> str:
    if not takhrij:
        return "unknown"
    return "in_sahihayn" if SAHIHAYN_RE.search(normalize(takhrij, "cer_loose")) else "other"


def dorar_search_url(hadith_text: str) -> str:
    words = normalize(hadith_text).split()[:10]
    return "https://dorar.net/hadith/search?q=" + urllib.parse.quote(" ".join(words))


def load_gradings() -> dict:
    return json.loads(GRADINGS.read_text()) if GRADINGS.exists() else {}


def units(blocks: list[dict]) -> list[dict]:
    """Group a document's matn blocks (reading order, all pages) into hadith units."""
    out: list[dict] = []
    cur: dict | None = None
    for b in blocks:
        if b.get("author_role") == "editor" or b["type"] in (
            "footnote",
            "page_number",
            "page_header",
        ):
            continue
        if b["type"] == "heading":
            cur = None
            continue
        if b["type"] == "body" and START_RE.match(b["text"]):
            cur = {"block_ids": [], "narration": [], "wording": [], "takhrij": None}
            out.append(cur)
        if cur is None:
            continue
        cur["block_ids"].append(b["id"])
        if b["type"] == "hadith":
            cur["wording"].append(b["text"])
        else:
            cur["narration"].append(b["text"])
            m = TAKHRIJ_RE.search(b["text"])
            if m and cur["takhrij"] is None:
                cur["takhrij"] = m.group(1).strip()
    gradings = load_gradings()
    res = []
    for i, u in enumerate(out):
        if not u["wording"] and not u["takhrij"]:
            continue  # narration without a quoted hadith (e.g. a companion's report)
        uid = f"h{i:03d}-{u['block_ids'][0]}"
        wording = " ".join(u["wording"]) or " ".join(u["narration"])
        kind = classify_takhrij(u["takhrij"])
        g = gradings.get(uid)
        if kind == "in_sahihayn":
            status, grading, url = "in_sahihayn", None, None
        elif g and g.get("grading") and g.get("url"):
            status, grading, url = "verified", g["grading"], g["url"]
        else:
            status, grading, url = "unverified", None, None
        res.append(
            {
                "id": uid,
                "block_ids": u["block_ids"],
                "wording": wording,
                "takhrij_text": u["takhrij"],
                "takhrij_kind": kind,
                "grading_status": status,
                "grading": grading,
                "grading_source_url": url,
                "graded_by": (g or {}).get("by"),
                "dorar_search_url": dorar_search_url(wording),
            }
        )
    return res
