"""Download «التفسير الميسر» (King Fahd Complex) from QuranEnc (موسوعة القرآن الكريم), an
approved platform in the challenge's scientific package (p.9). Used to show the meaning of a
verified verse, attributed to its source; never generated by a model.

Writes data/reference/quranenc/arabic_moyassar.json  {"s:a": text}. 114 polite requests.
Not committed (redistribution through QuranEnc's own API/site).
"""

from __future__ import annotations

import json
import time
import urllib.request
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "data" / "reference" / "quranenc" / "arabic_moyassar.json"
URL = "https://quranenc.com/api/v1/translation/sura/arabic_moyassar/{}"


def main() -> None:
    if OUT.exists() and len(json.loads(OUT.read_text())) == 6236:
        print("tafsir ready")
        return
    out = {}
    for s in range(1, 115):
        req = urllib.request.Request(URL.format(s), headers={"User-Agent": "Asool research tool"})
        with urllib.request.urlopen(req, timeout=60) as r:
            for a in json.loads(r.read().decode())["result"]:
                out[f"{int(a['sura'])}:{int(a['aya'])}"] = a["translation"].strip()
        time.sleep(0.15)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(out, ensure_ascii=False))
    print(len(out), "ayahs of tafsir saved")


if __name__ == "__main__":
    main()
