"use client";

import { useState } from "react";
import { ar } from "@/lib/api";
import { useT } from "@/lib/i18n";
import type { Hadith, QuranRef, Tafsir } from "@/lib/types";

/** Meaning of a verse from an approved tafsir (never generated), with its source. */
export function VerseMeaning({ t, open = false }: { t?: Tafsir; open?: boolean }) {
  if (!t) return null;
  return (
    <details className="mt-2 text-sm" open={open}>
      <summary className="cursor-pointer text-muted">المعنى من تفسير معتمد</summary>
      {t.text ? (
        <p className="mt-1 leading-loose">{t.text}</p>
      ) : (
        <p className="mt-1 text-muted">النص غير متاح محليًا؛ يُرجى فتح المصدر.</p>
      )}
      <p className="mt-1 text-xs text-muted">
        المصدر: {t.source}{" "}
        <a href={t.url} target="_blank" rel="noreferrer" className="text-insight underline">
          افتح ↗
        </a>
        {" · "}ليس من توليد النموذج.
      </p>
    </details>
  );
}

/** Compact verse badge: surah:ayah + verification status, linking to Quranpedia. */
export function VerseChip({ q }: { q: QuranRef }) {
  const exact = q.match_type === "exact";
  const url = q.quranpedia_url ?? `https://quranpedia.net/surah/${q.surah}/${q.ayah_start}`;
  const range = q.ayah_end !== q.ayah_start ? `${ar(q.ayah_start)}–${ar(q.ayah_end)}` : ar(q.ayah_start);
  const cls = exact
    ? "bg-thread/20 text-thread-strong"
    : q.match_type === "minor_variant"
      ? "bg-amber/25 text-amber-ink"
      : "bg-madder/15 text-madder";
  return (
    <a href={url} target="_blank" rel="noreferrer" className={`inline-block whitespace-nowrap rounded px-2 py-0.5 text-xs font-medium ${cls}`}>
      آية · سورة {ar(q.surah)}: {range} · {exact ? "✓ مطابقة للمصحف" : q.match_type === "minor_variant" ? "⚠ فرق يسير" : "✗ لا تطابق المصحف"} ↗
    </a>
  );
}

export function QuranCheck({ q }: { q: QuranRef }) {
  const exact = q.match_type === "exact";
  const url = q.quranpedia_url ?? `https://quranpedia.net/surah/${q.surah}/${q.ayah_start}`;
  const range = q.ayah_end !== q.ayah_start ? `${ar(q.ayah_start)}–${ar(q.ayah_end)}` : ar(q.ayah_start);
  return (
    <div className="rounded-md border border-line bg-surface p-3 text-sm">
      <div className="flex flex-wrap items-center gap-2">
        <span
          className={`rounded px-2 py-0.5 font-medium ${exact ? "bg-thread/20 text-thread-strong" : q.match_type === "minor_variant" ? "bg-amber/25 text-amber-ink" : "bg-madder/15 text-madder"}`}
        >
          {exact ? "✓ مطابقة للمصحف" : q.match_type === "minor_variant" ? "⚠ فرق يسير" : "✗ لا تطابق المصحف"}
        </span>
        <a href={url} target="_blank" rel="noreferrer" className="rounded border border-line px-2 py-0.5 text-insight">
          سورة {ar(q.surah)}: {range} ↗
        </a>
      </div>
      {!exact && q.diff_ops.length > 0 && (
        <ul className="mt-2 grid gap-1">
          {q.diff_ops.map((o, i) => (
            <li key={i}>
              المطبوع: <span className="font-source text-madder">{o.printed.join(" ") || "—"}</span> · في المصحف:{" "}
              <span className="font-source text-thread-strong">{o.reference.join(" ") || "—"}</span>
            </li>
          ))}
        </ul>
      )}
      <VerseMeaning t={q.tafsir} />
      <details className="mt-2">
        <summary className="cursor-pointer text-muted">نص المصحف (رواية حفص، مجمع الملك فهد)</summary>
        <p className="quran-text mt-1 text-lg">{q.canonical_text}</p>
        <p className="mt-1 text-xs text-muted">لم يُغيَّر النص المطبوع؛ نص المصحف معروض بجانبه للمقارنة فقط.</p>
      </details>
    </div>
  );
}

const GRADED = ["in_sahihayn", "hadeethenc", "dorar_manual"];

/** Short source label shown after the grading, e.g. «حسن · HadeethEnc». */
function gradeLabel(h: Hadith): string {
  if (!GRADED.includes(h.grading_status)) return "الحكم غير متحقق في البيانات";
  if (h.grading_status === "in_sahihayn") return h.grading;
  const src = h.grading_status === "hadeethenc" ? "HadeethEnc" : h.grading_status === "dorar_manual" ? "الدرر السنية" : h.grading_source;
  return src ? `${h.grading} · ${src}` : h.grading;
}

/** Compact grading chip: the grading and its source. Never generated by a model. */
export function GradeChip({ h }: { h: Hadith }) {
  const ok = GRADED.includes(h.grading_status);
  const label = (
    <>
      {ok ? "✓ " : "⚠ "}
      {gradeLabel(h)}
    </>
  );
  const cls = `inline-block whitespace-nowrap rounded px-2 py-0.5 text-xs font-medium ${ok ? "bg-thread/20 text-thread-strong" : "bg-amber/25 text-amber-ink"}`;
  return h.grading_source_url ? (
    <a className={`${cls} underline-offset-2 hover:underline`} href={h.grading_source_url} target="_blank" rel="noreferrer">
      {label} ↗
    </a>
  ) : (
    <span className={cls}>{label}</span>
  );
}

/** One-line grading badge placed beside al-Nawawi's printed takhrij (used under answer quotes). */
export function HadithBadge({ h }: { h: Hadith }) {
  return (
    <p className="mt-1 flex flex-wrap items-center gap-2 text-sm">
      <span className="text-muted">
        تخريج الإمام النووي: <strong className="text-foreground">{h.takhrij_printed ?? "غير موجود في صفحات المدونة"}</strong>
      </span>
      <GradeChip h={h} />
    </p>
  );
}

export function HadithGrade({ h }: { h: Hadith }) {
  return (
    <div className="rounded-md border border-line bg-surface p-3 text-sm">
      <div className="flex flex-wrap items-center gap-2">
        <span className="font-medium">حكم الحديث:</span>
        <GradeChip h={h} />
      </div>
      <p className="mt-1">
        تخريج الإمام النووي كما طُبع: <strong>{h.takhrij_printed ?? "غير موجود في صفحات المدونة"}</strong>
      </p>
      <a className="mt-1 inline-block text-xs text-insight underline" href={h.dorar_search_url} target="_blank" rel="noreferrer">
        ابحث عنه في الدرر السنية ↗
      </a>
    </div>
  );
}

export function CopyCitation({ text, citation }: { text: string; citation: string }) {
  const t = useT();
  const [done, setDone] = useState(false);
  return (
    <button
      className="rounded border border-line px-2 py-0.5 text-xs"
      onClick={async () => {
        try {
          await navigator.clipboard.writeText(`«${text}»\n— ${citation}`);
          setDone(true);
          setTimeout(() => setDone(false), 1500);
        } catch {
          /* clipboard blocked */
        }
      }}
    >
      {done ? `✓ ${t("copied")}` : t("copy_cite")}
    </button>
  );
}

export function LevelBadge({ level }: { level: string | null }) {
  if (!level) return null;
  const tip: Record<string, string> = {
    A: "معلومات أصلية مستقرة: إجابة مباشرة موثقة بالمصدر",
    B: "شرح وتعريف واستدلال: من المادة المعتمدة مع إظهار المرجع",
    C: "مسألة خلافية أو عالية الحساسية: إجابة مقيدة مع بيان وجود الخلاف والإحالة",
    D: "فتوى أو حالة شخصية: لا يُصدر النظام حكمًا ويحيل إلى جهة مؤهلة",
  };
  return (
    <span title={tip[level]} className="rounded border border-line px-2 py-0.5 text-xs">
      مستوى المحتوى: {level === "A" ? "أ" : level === "B" ? "ب" : level === "C" ? "ج" : "د"}
    </span>
  );
}
