"""Hadith grading review (owner rule, Oct 4, CLAUDE.md §12.F).

1. Takhrij names al-Bukhari/Muslim -> «في الصحيحين» (automatic, from the printed takhrij).
2. Otherwise HadeethEnc match with the same narrator and core wording -> its grade + link
   (automatic). An uncertain match waits for the owner to confirm or reject it here.
3. Not in HadeethEnc -> the owner enters the dorar.net result here: grading, muhaddith,
   source, number, link. A warning is shown when the entered narrator differs from the book.
4. Nothing -> «الحكم غير متحقق في البيانات».
Decisions are stored in data/hadith_gradings.json (versioned) and applied to the index.
A grading is never generated by a model.
"""

from __future__ import annotations

import json
import sqlite3
import threading
from datetime import UTC, datetime

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel

from api.gold_review import _auth
from pipeline.config import DATA
from pipeline.hadith import GRADINGS, UNVERIFIED_AR, same_narrator

router = APIRouter(prefix="/review/hadith", tags=["hadith review"], dependencies=[Depends(_auth)])
_lock = threading.Lock()
DB = DATA / "asool.db"

STATUS_AR = {
    "in_sahihayn": "في الصحيحين",
    "hadeethenc": "حكم موسوعة الأحاديث النبوية",
    "hadeethenc_pending": "مطابقة غير مؤكدة: تحتاج تأكيدك",
    "dorar_manual": "حكم من الدرر السنية (إدخال يدوي)",
    "unverified": UNVERIFIED_AR,
}


def _rows() -> list[dict]:
    con = sqlite3.connect(DB)
    con.row_factory = sqlite3.Row
    rows = [dict(r) for r in con.execute("SELECT * FROM hadith_marks ORDER BY id")]
    pages = {r["id"]: r["page_id"] for r in con.execute("SELECT id, page_id FROM blocks")}
    con.close()
    for r in rows:
        for k in ("block_ids", "hadeethenc", "hadeethenc_check", "dorar_entry"):
            r[k] = json.loads(r[k]) if r[k] else ([] if k in ("block_ids", "hadeethenc") else None)
        r["page_ids"] = sorted({pages[b] for b in r["block_ids"] if b in pages})
        r["status_ar"] = STATUS_AR.get(r["grading_status"], UNVERIFIED_AR)
    return rows


def _save_grading(hid: str, entry: dict | None) -> None:
    g = json.loads(GRADINGS.read_text()) if GRADINGS.exists() else {}
    if entry is None:
        g.pop(hid, None)
    else:
        g[hid] = entry
    GRADINGS.write_text(json.dumps(g, ensure_ascii=False, indent=1))


def _update(hid: str, **fields) -> None:
    con = sqlite3.connect(DB)
    sets = ", ".join(f"{k}=?" for k in fields)
    vals = [
        json.dumps(v, ensure_ascii=False) if isinstance(v, dict) else v for v in fields.values()
    ]
    con.execute(f"UPDATE hadith_marks SET {sets} WHERE id=?", (*vals, hid))
    con.commit()
    con.close()


def _get(hid: str) -> dict:
    row = next((r for r in _rows() if r["id"] == hid), None)
    if not row:
        raise HTTPException(404, "hadith not found")
    if row["grading_status"] == "in_sahihayn":
        raise HTTPException(409, "هذا الحديث في الصحيحين بحسب تخريج المصنف؛ لا يحتاج حكمًا خارجيًا")
    return row


@router.get("")
def list_hadith(needs_grading_only: bool = True) -> list[dict]:
    return [r for r in _rows() if not needs_grading_only or r["takhrij_kind"] != "in_sahihayn"]


class Confirm(BaseModel):
    accept: bool
    reviewer: str


@router.post("/{hid}/hadeethenc")
def confirm_hadeethenc(hid: str, body: Confirm) -> dict:
    """Owner confirms or rejects an uncertain HadeethEnc match."""
    with _lock:
        row = _get(hid)
        if not row["hadeethenc"]:
            raise HTTPException(409, "no HadeethEnc match for this hadith")
        he = row["hadeethenc"][0]
        now = datetime.now(UTC).isoformat()
        if body.accept:
            _save_grading(
                hid,
                {"type": "hadeethenc_confirmed", "he_id": he["id"], "by": body.reviewer, "at": now},
            )
            _update(
                hid,
                grading_status="hadeethenc",
                grading=he.get("grade"),
                grading_source="موسوعة الأحاديث النبوية (HadeethEnc)",
                grading_source_url=he.get("url"),
                graded_by=body.reviewer,
            )
        else:
            _save_grading(
                hid,
                {"type": "hadeethenc_rejected", "he_id": he["id"], "by": body.reviewer, "at": now},
            )
            _update(
                hid,
                grading_status="unverified",
                grading=None,
                grading_source=None,
                grading_source_url=None,
                graded_by=None,
            )
    return {"ok": True}


class DorarEntry(BaseModel):
    grading: str
    muhaddith: str
    source: str
    number: str
    url: str
    narrator: str = ""
    reviewer: str


@router.post("/{hid}/dorar")
def save_dorar(hid: str, body: DorarEntry) -> dict:
    url = body.url.strip()
    if not url.startswith(("https://dorar.net/", "https://www.dorar.net/")):
        raise HTTPException(422, "الرابط يجب أن يكون من موقع الدرر السنية dorar.net")
    missing = [
        k for k in ("grading", "muhaddith", "source", "number") if not getattr(body, k).strip()
    ]
    if missing:
        raise HTTPException(422, "أكمل الحقول المطلوبة: الحكم، المحدث، المصدر، الرقم")
    with _lock:
        row = _get(hid)
        warn = None
        if body.narrator.strip() and same_narrator(body.narrator, row["narrator"]) is False:
            warn = (
                f"الراوي المُدخل «{body.narrator.strip()}» يختلف عن راوي الكتاب "
                f"«{row['narrator']}». تأكد أنه الحديث نفسه."
            )
        entry = {
            "type": "dorar",
            "grading": body.grading.strip(),
            "muhaddith": body.muhaddith.strip(),
            "source": body.source.strip(),
            "number": body.number.strip(),
            "url": url,
            "narrator": body.narrator.strip(),
            "narrator_warning": warn,
            "by": body.reviewer,
            "at": datetime.now(UTC).isoformat(),
        }
        _save_grading(hid, entry)
        _update(
            hid,
            grading_status="dorar_manual",
            grading=entry["grading"],
            grading_source=f"الدرر السنية: {entry['muhaddith']} — {entry['source']} "
            f"({entry['number']})",
            grading_source_url=url,
            graded_by=body.reviewer,
            dorar_entry=entry,
        )
    return {"ok": True, "warning": warn}


@router.delete("/{hid}")
def clear(hid: str) -> dict:
    with _lock:
        _get(hid)
        _save_grading(hid, None)
        _update(
            hid,
            grading_status="unverified",
            grading=None,
            grading_source=None,
            grading_source_url=None,
            graded_by=None,
            dorar_entry=None,
        )
    return {"ok": True, "note": "rebuild the index to re-apply automatic HadeethEnc matches"}
