"""Human entry of hadith gradings from dorar.net (owner decision, Oct 4).

Only hadiths outside the Sahihayn need a grading. The reviewer opens the prefilled dorar.net
search link, then pastes the grading text and the dorar result URL. Stored in
data/hadith_gradings.json (versioned in git: it is human-verified data) and mirrored into the
index. A grading is never generated by a model.
"""

from __future__ import annotations

import json
import sqlite3
import threading
from datetime import UTC, datetime

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel

from api.gold_review import _auth
from pipeline.config import DATA
from pipeline.hadith import GRADINGS, UNVERIFIED_AR

router = APIRouter(prefix="/review/hadith", tags=["hadith review"], dependencies=[Depends(_auth)])
_lock = threading.Lock()
DB = DATA / "asool.db"


def _rows() -> list[dict]:
    con = sqlite3.connect(DB)
    con.row_factory = sqlite3.Row
    rows = [dict(r) for r in con.execute("SELECT * FROM hadith_marks ORDER BY id")]
    pages = {r["id"]: r["page_id"] for r in con.execute("SELECT id, page_id FROM blocks")}
    con.close()
    for r in rows:
        r["block_ids"] = json.loads(r["block_ids"])
        r["hadeethenc"] = json.loads(r["hadeethenc"] or "[]")
        r["page_ids"] = sorted({pages[b] for b in r["block_ids"] if b in pages})
        r["display_status"] = (
            "في الصحيحين بحسب تخريج المصنف"
            if r["grading_status"] == "in_sahihayn"
            else (r["grading"] if r["grading_status"] == "verified" else UNVERIFIED_AR)
        )
    return rows


@router.get("")
def list_hadith(needs_grading_only: bool = True) -> list[dict]:
    rows = _rows()
    return [r for r in rows if not needs_grading_only or r["grading_status"] != "in_sahihayn"]


class Grading(BaseModel):
    grading: str
    url: str
    reviewer: str


@router.post("/{hid}")
def save(hid: str, body: Grading) -> dict:
    url = body.url.strip()
    if not url.startswith(("https://dorar.net/", "https://www.dorar.net/")):
        raise HTTPException(422, "الرابط يجب أن يكون من موقع الدرر السنية dorar.net")
    if not body.grading.strip():
        raise HTTPException(422, "أدخل نص الحكم كما في الدرر السنية")
    with _lock:
        rows = {r["id"]: r for r in _rows()}
        if hid not in rows:
            raise HTTPException(404, "hadith not found")
        if rows[hid]["grading_status"] == "in_sahihayn":
            raise HTTPException(409, "this hadith is in the Sahihayn; no external grading needed")
        g = json.loads(GRADINGS.read_text()) if GRADINGS.exists() else {}
        g[hid] = {
            "grading": body.grading.strip(),
            "url": url,
            "by": body.reviewer,
            "at": datetime.now(UTC).isoformat(),
            "wording_start": rows[hid]["wording"][:80],
        }
        GRADINGS.write_text(json.dumps(g, ensure_ascii=False, indent=1))
        con = sqlite3.connect(DB)
        con.execute(
            "UPDATE hadith_marks SET grading_status='verified', grading=?, grading_source_url=?, "
            "graded_by=? WHERE id=?",
            (body.grading.strip(), url, body.reviewer, hid),
        )
        con.commit()
        con.close()
    return {"ok": True}


@router.delete("/{hid}")
def clear(hid: str) -> dict:
    with _lock:
        g = json.loads(GRADINGS.read_text()) if GRADINGS.exists() else {}
        g.pop(hid, None)
        GRADINGS.write_text(json.dumps(g, ensure_ascii=False, indent=1))
        con = sqlite3.connect(DB)
        con.execute(
            "UPDATE hadith_marks SET grading_status='unverified', grading=NULL, "
            "grading_source_url=NULL, graded_by=NULL WHERE id=? AND grading_status='verified'",
            (hid,),
        )
        con.commit()
        con.close()
    return {"ok": True}
